name: from-url

on:
  workflow_dispatch:
    inputs:
      remote_url:
        description: "remote url"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: 'requirements.*.txt'
      - run: pip install -r requirements.from-url.txt
      - run: python from-url.py "${{inputs.remote_url}}"
        env:
          OSS_BUCKET: ${{secrets.OSS_BUCKET}}
          OSS_ENDPOINT: ${{secrets.OSS_ENDPOINT}}
          OSS_ACCESS_KEY_ID: ${{secrets.OSS_ACCESS_KEY_ID}}
          OSS_ACCESS_KEY_SECRET: ${{secrets.OSS_ACCESS_KEY_SECRET}}
